# Generated by Django 4.0.5 on 2022-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextAudioMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_filename', models.CharField(default=None, max_length=200, null=True)),
                ('last_accessed', models.DateField(default=None, null=True)),
                ('text', models.CharField(default=None, max_length=300, null=True)),
                ('uploaded_by', models.CharField(default=None, max_length=200, null=True)),
                ('was_accessed', models.BooleanField(default=None)),
            ],
        ),
    ]
