# Generated by Django 4.0.5 on 2022-06-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textaudiomap',
            name='last_accessed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
