# Generated by Django 4.0.5 on 2022-06-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textaudiomap',
            name='was_accessed',
        ),
        migrations.AddField(
            model_name='textaudiomap',
            name='audio_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textaudiomap',
            name='audio_filename',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textaudiomap',
            name='last_accessed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textaudiomap',
            name='uploaded_by',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
