# Generated by Django 4.0.5 on 2022-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0002_remove_textaudiomap_was_accessed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textaudiomap',
            name='audio_url',
            field=models.URLField(blank=True, default=None, max_length=3000, null=True),
        ),
    ]
