# Generated by Django 4.0.5 on 2022-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0002_alter_textaudiomap_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textaudiomap',
            name='audio_filename',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textaudiomap',
            name='uploaded_by',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
