# Generated by Django 4.0.5 on 2022-06-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0003_alter_textaudiomap_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_tried', models.DateTimeField(default=None, null=True)),
                ('last_upload', models.DateTimeField(default=None, null=True)),
                ('n_tries', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False, null=True)),
                ('user_uid', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
