# Generated by Django 4.0.5 on 2022-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0004_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='n_uploads',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
