# Generated by Django 4.0.5 on 2022-07-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0005_useractivity_n_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textaudiomap',
            name='text',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
